[package]
name = "tir-symbolic"
version = "0.1.0"
edition = "2024"

[lib]
bench = false
test = false
doctest = false

[dependencies]
tir-graph.workspace = true
tir-adt.workspace = true
chumsky.workspace = true

[[bin]]
bench = false
name = "tir-smt"
path = "src/bin/main.rs"

[lints]
workspace = true
