[package]
name = "tir-symbolic"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doctest = false

[dependencies]
tir-graph.workspace = true
tir-adt.workspace = true
tir-relational.workspace = true
chumsky.workspace = true
smallvec = "1.15.2"

[[bin]]
name = "tir-smt"
path = "src/bin/main.rs"

[dev-dependencies]
criterion = { workspace = true }
egg = "0.11"

[[bench]]
name = "egraph"
harness = false

[[bench]]
name = "egg_math"
harness = false
