pub mod affine;
pub mod alias_facts;
pub mod constant_facts;
pub mod defuse;
mod dominance;
mod edge_facts;
pub mod escape_facts;
mod manager;
pub mod scopes;
pub mod slots;
pub mod solver;

pub use affine::AffineView;
pub use alias_facts::{AliasFacts, AliasResult, Base, PointerFact};
pub use constant_facts::{ConstantFacts, Fact};
pub use defuse::{DefUse, OpRegs, PhysReg, execution_regs, op_regs};
pub use dominance::*;
pub use edge_facts::*;
pub use escape_facts::{Escape, EscapeFacts};
pub use manager::*;
