[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
xshell = "0.2.7"
tir-isa-test-suite = { path = "../utils/isa-test-suite" }
tir-verify = { path = "../utils/verify" }
tmdl.workspace = true

[lints]
workspace = true
