[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
tir-bench.workspace = true
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
toml.workspace = true
regex.workspace = true
sha2 = "0.8.2"
tempfile = "3.27.0"
xshell = "0.2.7"
tir-isa-test-suite = { path = "../utils/isa-test-suite" }
tir-verify = { path = "../utils/verify" }
tmdl.workspace = true

[lints]
workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"
bench = false
