; Target-independent instruction-selection invariants.
(theory
  (axiom sext-bridge (vars (x n)) (root w) (where (< n w))
    (lhs (sext x w)) (rhs (ashr (shl x (- w n)) (- w n))))

  (axiom zext-mask (vars (x n)) (root w) (where (< n w))
    (lhs (zext x w)) (rhs (and (ones n) x)))
  (axiom zext-shifts (vars (x n)) (root w) (where (< n w))
    (lhs (zext x w)) (rhs (lshr (shl x (- w n)) (- w n))))

  (axiom if-same (vars (c 1) (x w)) (root w)
    (lhs (if c x x)) (rhs x))
  (axiom if-then-condition (vars (c 1) (x 1)) (root 1)
    (lhs (if c c x)) (rhs (if c (const 1 1) x)))
  (axiom if-else-condition (vars (c 1) (x 1)) (root 1)
    (lhs (if c x c)) (rhs (if c x (const 0 1))))
  (axiom theta-same (vars (x w)) (root w)
    (lhs (theta x x)) (rhs x))

  ; Zero-register comparison shapes: applied once after the saturation fixpoint,
  ; so the synthetic zero cannot feed back through the boolean `*-via-if`
  ; identities and multiply equivalent comparison forms.
  (axiom eq-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (eq x 0))
    (rhs (eq x (zext (const 0 1) w))))
  (axiom ne-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ne x 0))
    (rhs (ne x (zext (const 0 1) w))))
  (axiom lt-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (lt x 0))
    (rhs (lt x (zext (const 0 1) w))))
  (axiom zero-lt (vars (x w)) (root 1) (phase post-saturation)
    (lhs (lt 0 x))
    (rhs (lt (zext (const 0 1) w) x)))
  (axiom le-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (le x 0))
    (rhs (le x (zext (const 0 1) w))))
  (axiom zero-le (vars (x w)) (root 1) (phase post-saturation)
    (lhs (le 0 x))
    (rhs (le (zext (const 0 1) w) x)))
  (axiom gt-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (gt x 0))
    (rhs (gt x (zext (const 0 1) w))))
  (axiom zero-gt (vars (x w)) (root 1) (phase post-saturation)
    (lhs (gt 0 x))
    (rhs (gt (zext (const 0 1) w) x)))
  (axiom ge-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ge x 0))
    (rhs (ge x (zext (const 0 1) w))))
  (axiom zero-ge (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ge 0 x))
    (rhs (ge (zext (const 0 1) w) x)))
  (axiom ult-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ult x 0))
    (rhs (ult x (zext (const 0 1) w))))
  (axiom zero-ult (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ult 0 x))
    (rhs (ult (zext (const 0 1) w) x)))
  (axiom ule-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ule x 0))
    (rhs (ule x (zext (const 0 1) w))))
  (axiom zero-ule (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ule 0 x))
    (rhs (ule (zext (const 0 1) w) x)))
  (axiom ugt-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ugt x 0))
    (rhs (ugt x (zext (const 0 1) w))))
  (axiom zero-ugt (vars (x w)) (root 1) (phase post-saturation)
    (lhs (ugt 0 x))
    (rhs (ugt (zext (const 0 1) w) x)))
  (axiom uge-zero (vars (x w)) (root 1) (phase post-saturation)
    (lhs (uge x 0))
    (rhs (uge x (zext (const 0 1) w))))
  (axiom zero-uge (vars (x w)) (root 1) (phase post-saturation)
    (lhs (uge 0 x))
    (rhs (uge (zext (const 0 1) w) x)))

  (axiom neg-sub (vars (x w)) (root w) (lhs (neg x)) (rhs (sub 0 x)))
  (axiom neg-mul (vars (x w)) (root w) (lhs (neg x)) (rhs (mul (ones w) x)))

  (axiom not-sub (vars (x w)) (root w) (lhs (not x)) (rhs (sub (ones w) x)))
  (axiom not-sub-one (vars (x w)) (root w) (lhs (not x)) (rhs (sub (sub 0 x) 1)))
  (axiom not-xor (vars (x w)) (root w) (lhs (not x)) (rhs (xor (ones w) x)))
  (axiom not-add-sub (vars (x w)) (root w) (lhs (not x)) (rhs (sub 0 (add 1 x))))

  (axiom eq-via-if (root 1) (lhs (eq a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom ne-via-if (root 1) (lhs (ne a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom lt-via-if (root 1) (lhs (lt a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom le-via-if (root 1) (lhs (le a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom gt-via-if (root 1) (lhs (gt a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom ge-via-if (root 1) (lhs (ge a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom ult-via-if (root 1) (lhs (ult a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom ule-via-if (root 1) (lhs (ule a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom ugt-via-if (root 1) (lhs (ugt a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom uge-via-if (root 1) (lhs (uge a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom and-via-if (vars (a 1) (b 1)) (root 1) (lhs (and a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))
  (axiom xor-via-if (vars (a 1) (b 1)) (root 1) (lhs (xor a b))
    (rhs (if root (zext (const 1 1) (const 1 1)) (zext (const 0 1) (const 1 1)))))

  (axiom eq-via-cmp (vars (a w) (b w)) (root 1) (lhs (eq a b)) (rhs (ult (xor a b) 1)))
  (axiom ne-via-cmp (vars (a w) (b w)) (root 1) (lhs (ne a b)) (rhs (xor (ult (xor a b) 1) (const 1 1))))
  (axiom ge-via-cmp (vars (a w) (b w)) (root 1) (lhs (ge a b)) (rhs (xor (lt a b) (const 1 1))))
  (axiom le-via-cmp (vars (a w) (b w)) (root 1) (lhs (le a b)) (rhs (xor (lt b a) (const 1 1))))
  (axiom uge-via-cmp (vars (a w) (b w)) (root 1) (lhs (uge a b)) (rhs (xor (ult a b) (const 1 1))))
  (axiom ule-via-cmp (vars (a w) (b w)) (root 1) (lhs (ule a b)) (rhs (xor (ult b a) (const 1 1))))

  (axiom sub-via-add-neg (vars (a w)) (consts (c w)) (root w)
    (lhs (sub a c)) (rhs (add a (neg c)))))
