[package]
name = "tir-isasim"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tir-isasim"
path = "src/main.rs"
test = false
doctest = false

[dependencies]
tir.workspace = true
tir-sim.workspace = true
tir-riscv.workspace = true
tir-arm64.workspace = true
tir-x86_64.workspace = true
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[lints]
workspace = true
