//! Target-independent performance / scheduling model.
//!
//! This is the runtime counterpart of TMDL's `machine`, `unit`, and `schedule`
//! constructs, generated by the TMDL compiler exactly like
//! [`crate::backend::regalloc::RegisterInfo`] is. One [`MachineModel`] describes a single
//! device implementation: its issue width, functional-unit resources, structural
//! buffer sizes, and the per-instruction scheduling classes obtained by resolving
//! each instruction's `unit` membership against that machine's `bind`s.
//!
//! Both the compiler cost model and the cycle-approximate simulator consume this
//! single source of truth, so they can never disagree about an instruction's cost.

/// One functional unit / issue resource of a machine (e.g. `ALU`, `MUL`, `LSU`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProcUnit {
    pub name: &'static str,
    /// Number of parallel units of this resource.
    pub units: u16,
}

/// Structural buffer size of a machine (e.g. `rob`, `lsq`, `iq`). These are
/// *defaults* declared in TMDL; the Rust simulator may override them per run.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BufferSize {
    pub name: &'static str,
    pub size: u32,
}

/// The number of physical registers in one register file, used to model renaming
/// pressure on an out-of-order core. `name` is the physical-file name (the root of
/// a register class's inheritance chain; see `RegisterClass::register_file`), so
/// aliasing classes share one entry. A file a machine does not declare defaults to
/// its architectural register count (resolved by the consumer).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RegFile {
    pub name: &'static str,
    pub count: u16,
}

/// How a pipeline stage handles data hazards — determines whether the simulator
/// (and compiler) must honor a latency by stalling, or whether timing is exposed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Protection {
    /// Hardware interlocks: the machine stalls to honor producer→consumer latency.
    /// The norm for superscalar CPUs.
    Protected,
    /// No interlock: the compiler must schedule around the latency (exposed
    /// pipelines, typical of DSPs). The simulator assumes no stall.
    Unprotected,
    /// Fixed side-effect timing that cannot be stalled (e.g. branch delay slots).
    Hard,
}

/// One named stage of a machine's pipeline. Its position in
/// [`MachineModel::pipeline`] is its cycle offset from issue.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PipelinePhase {
    pub name: &'static str,
    pub protection: Protection,
}

/// A forwarding/bypass path: a result produced by an instruction occupying the
/// `from` resource can be consumed by an instruction on the `to` resource with
/// `latency` cycles of producer→consumer delay, instead of the producer's default
/// latency. Models the bypass network that lets dependent ops run back-to-back.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Forward {
    pub from: &'static str,
    pub to: &'static str,
    pub latency: u16,
}

/// The concrete scheduling cost of an instruction on a particular machine: the
/// resolution of its `unit` membership against that machine's `bind`s.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstrSchedClass {
    /// Producer→consumer latency, in cycles: the gap between the cycle operands are
    /// read and the cycle the result is produced (`write_cycle - read_cycle`).
    pub latency: u16,
    /// The cycle, relative to issue, at which source operands are consumed. `0` for
    /// the scalar `latency = N` form; non-zero when a `bind` reads at a later
    /// pipeline phase. Used for forwarding/bypass and exposed-pipeline modeling.
    pub read_cycle: u16,
    /// Reciprocal throughput, in cycles (the issue interval). `1` means the
    /// instruction can issue every cycle.
    pub rthroughput: u16,
    /// Resources (by [`ProcResource::name`]) this instruction occupies.
    pub resources: &'static [&'static str],
}

impl InstrSchedClass {
    /// The fallback class for instructions a machine does not model: single-cycle,
    /// fully pipelined, occupying no named resource. This matches the built-in
    /// default the cost model assumes when no `schedule`/`bind` applies.
    pub const DEFAULT: InstrSchedClass = InstrSchedClass {
        latency: 1,
        read_cycle: 0,
        rthroughput: 1,
        resources: &[],
    };

    /// The cycle, relative to issue, at which the result becomes available.
    pub fn write_cycle(&self) -> u16 {
        self.read_cycle.saturating_add(self.latency)
    }
}

/// One device implementation's static performance model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MachineModel {
    pub name: &'static str,
    pub issue_width: u16,
    pub resources: &'static [ProcUnit],
    pub buffers: &'static [BufferSize],
    /// Ordered pipeline stages; each phase's index is its cycle offset from issue.
    /// Empty when the machine declares no `pipeline` (e.g. an out-of-order core
    /// whose timing is given as scalar latencies).
    pub pipeline: &'static [PipelinePhase],
    /// Forwarding/bypass paths between resources.
    pub forwards: &'static [Forward],
    /// Physical register-file sizes for renaming, keyed by physical-file name. A
    /// file absent here defaults to its architectural register count.
    pub reg_files: &'static [RegFile],
    /// Per-instruction scheduling classes keyed by operation mnemonic, sorted by
    /// mnemonic for binary search. Resolved at TMDL-compile time.
    pub sched: &'static [(&'static str, InstrSchedClass)],
}

impl MachineModel {
    /// The scheduling class for an operation mnemonic, or [`InstrSchedClass::DEFAULT`]
    /// if this machine has no specific entry for it.
    pub fn sched_class(&self, mnemonic: &str) -> InstrSchedClass {
        match self.sched.binary_search_by_key(&mnemonic, |(m, _)| m) {
            Ok(i) => self.sched[i].1,
            Err(_) => InstrSchedClass::DEFAULT,
        }
    }

    pub fn resource(&self, name: &str) -> Option<&ProcUnit> {
        self.resources.iter().find(|r| r.name == name)
    }

    /// The declared default size of a structural buffer (e.g. `"rob"`), if any.
    pub fn buffer(&self, name: &str) -> Option<u32> {
        self.buffers.iter().find(|b| b.name == name).map(|b| b.size)
    }

    /// The declared physical register count of a file (e.g. `"GPR"`), if any.
    pub fn reg_file(&self, name: &str) -> Option<u16> {
        self.reg_files
            .iter()
            .find(|f| f.name == name)
            .map(|f| f.count)
    }

    /// The cycle offset (index) of a named pipeline phase, if declared.
    pub fn phase_cycle(&self, name: &str) -> Option<u16> {
        self.pipeline
            .iter()
            .position(|p| p.name == name)
            .map(|i| i as u16)
    }

    /// The protection mode of the phase at the given cycle, if within the pipeline.
    pub fn protection_at(&self, cycle: u16) -> Option<Protection> {
        self.pipeline.get(cycle as usize).map(|p| p.protection)
    }

    /// The forwarded producer→consumer latency for a result moving from the `from`
    /// resource to the `to` resource, if a bypass path is declared.
    pub fn forward_latency(&self, from: &str, to: &str) -> Option<u16> {
        self.forwards
            .iter()
            .find(|f| f.from == from && f.to == to)
            .map(|f| f.latency)
    }
}
