//! Target-independent performance / scheduling model.
//!
//! This is the runtime counterpart of TMDL's `machine`, `unit`, and `schedule`
//! constructs, generated by the TMDL compiler exactly like
//! [`crate::backend::regalloc::RegisterInfo`] is. One [`MachineModel`] describes a single
//! device implementation: its issue width, functional-unit resources, structural
//! buffer sizes, and the per-instruction scheduling classes obtained by resolving
//! each instruction's `unit` membership against that machine's `bind`s.
//!
//! Instruction selection uses machine-independent scheduling-class defaults.
//! Static scheduling uses the machine class, including its fallback latency.
//! The simulator resolves conditional latency from values captured before execution.

/// One ordered scheduling predicate evaluated against the instruction's entry state.
pub struct LatencyCase {
    pub env: &'static super::exec::ExecEnv,
    pub sym_count: usize,
    pub sources: &'static [(usize, super::exec::SymSource)],
    /// Offset of a pure bits<1> expression in the semantic blob.
    pub condition: u32,
    pub latency: u16,
    /// Replacement micro-op routes, or `None` to inherit the fallback class.
    pub uops: Option<&'static [MicroOp]>,
}

impl LatencyCase {
    pub(super) fn matches(
        &self,
        instance: &crate::OpHandle,
        context: &mut dyn super::MachineContext,
        name: &'static str,
    ) -> Option<bool> {
        let syms =
            super::exec::init_syms(instance, context, name, self.sym_count, self.sources).ok()?;
        use crate::sem::ExtendSemBytes as _;
        let mut graph = crate::sem::SemGraph::new();
        graph.extend_sem_bytes(self.env.kinds, self.env.blob, self.condition);
        crate::sem::execute_pure(&graph, &syms).map(|value| !value.is_zero())
    }
}

/// One functional unit / issue resource of a machine (e.g. `ALU`, `MUL`, `LSU`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProcUnit {
    pub name: &'static str,
    /// Number of parallel units of this resource.
    pub units: u16,
}

/// Structural buffer size of a machine (e.g. `rob`, `lsq`, `iq`). These are
/// *defaults* declared in TMDL; the Rust simulator may override them per run.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BufferSize {
    pub name: &'static str,
    pub size: u32,
}

/// The number of physical registers in one register file, used to model renaming
/// pressure on an out-of-order core. `name` is the physical-file name (the root of
/// a register class's inheritance chain; see `RegisterClass::register_file`), so
/// aliasing classes share one entry. A file a machine does not declare defaults to
/// its architectural register count (resolved by the consumer).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RegFile {
    pub name: &'static str,
    pub count: u16,
}

/// How a pipeline stage handles data hazards — determines whether the simulator
/// (and compiler) must honor a latency by stalling, or whether timing is exposed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Protection {
    /// Hardware interlocks: the machine stalls to honor producer→consumer latency.
    /// The norm for superscalar CPUs.
    Protected,
    /// No interlock: the compiler must schedule around the latency (exposed
    /// pipelines, typical of DSPs). The simulator assumes no stall.
    Unprotected,
    /// Fixed side-effect timing that cannot be stalled (e.g. branch delay slots).
    Hard,
}

/// One named stage of a machine's pipeline. Its position in
/// [`MachineModel::pipeline`] is its cycle offset from issue.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PipelinePhase {
    pub name: &'static str,
    pub protection: Protection,
}

/// A forwarding/bypass path: a result produced by an instruction occupying the
/// `from` resource can be consumed by an instruction on the `to` resource with
/// `latency` cycles of producer→consumer delay, instead of the producer's default
/// latency. Models the bypass network that lets dependent ops run back-to-back.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Forward {
    pub from: &'static str,
    pub to: &'static str,
    pub latency: u16,
}

/// One concrete execution-resource reservation within a micro-op route.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResourceUse {
    pub resource: &'static str,
    pub cycles: u16,
}

/// Resources reserved together when this route is selected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResourceRoute {
    pub resources: &'static [ResourceUse],
}

/// One micro-op with one or more alternative execution routes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MicroOp {
    pub routes: &'static [ResourceRoute],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FrontendFetch {
    pub bytes_per_cycle: u16,
    pub window_bytes: u16,
    pub alignment: u16,
    pub queue_bytes: u16,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Decoder {
    pub name: &'static str,
    pub max_uops_per_instruction: u16,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FrontendDecode {
    pub slots: &'static [&'static str],
    pub uops_per_cycle: u16,
    pub queue_uops: u16,
    pub decoders: &'static [Decoder],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecodedCache {
    pub sets: u16,
    pub ways: u16,
    pub line_bytes: u16,
    pub line_uops: u16,
    pub deliver_uops_per_cycle: u16,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Frontend {
    pub fetch: FrontendFetch,
    pub decode: FrontendDecode,
    pub decoded_cache: Option<DecodedCache>,
}

/// The concrete scheduling cost of an instruction on a particular machine: the
/// resolution of its `unit` membership against that machine's `bind`s.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstrSchedClass {
    /// Producer→consumer latency, in cycles: the gap between the cycle operands are
    /// read and the cycle the result is produced (`write_cycle - read_cycle`).
    pub latency: u16,
    /// The cycle, relative to issue, at which source operands are consumed. `0` for
    /// the scalar `latency = N` form; non-zero when a `bind` reads at a later
    /// pipeline phase. Used for forwarding/bypass and exposed-pipeline modeling.
    pub read_cycle: u16,
    /// Reciprocal throughput, in cycles (the issue interval). `1` means the
    /// instruction can issue every cycle.
    pub rthroughput: u16,
    /// Resources (by [`ProcResource::name`]) this instruction occupies.
    pub resources: &'static [&'static str],
    /// Micro-op resource routes. Empty for the legacy `uses = [...]` form.
    pub uops: &'static [MicroOp],
    /// Number of micro-ops entering the frontend queues for this instruction.
    pub decode_uops: u16,
    /// Required decoder kind, or `None` when any capable slot may decode it.
    pub decoder: Option<&'static str>,
    /// Consecutive cycles for which the selected decoder slot remains occupied.
    pub decode_cycles: u16,
    /// The instruction completes in the rename stage: it reserves no execution
    /// resource and its result is available the cycle it issues (move
    /// elimination). It still costs front-end bandwidth, issue width and a ROB
    /// slot, and still waits for its sources.
    pub eliminated: bool,
    /// The instruction is a dependency-breaking idiom when its sources are a
    /// subset of its destinations (`xor eax, eax`). Such an instance drops its
    /// input dependencies and is handled like `eliminated`; other instances
    /// execute normally.
    pub zero_idiom: bool,
}

impl InstrSchedClass {
    /// The fallback class for instructions a machine does not model: single-cycle,
    /// fully pipelined, occupying no named resource. This matches the built-in
    /// default the cost model assumes when no `schedule`/`bind` applies.
    pub const DEFAULT: InstrSchedClass = InstrSchedClass {
        latency: 1,
        read_cycle: 0,
        rthroughput: 1,
        resources: &[],
        uops: &[],
        decode_uops: 1,
        decoder: None,
        decode_cycles: 1,
        eliminated: false,
        zero_idiom: false,
    };

    /// The cycle, relative to issue, at which the result becomes available.
    pub fn write_cycle(&self) -> u16 {
        self.read_cycle.saturating_add(self.latency)
    }
}

/// One device implementation's static performance model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MachineModel {
    pub name: &'static str,
    /// This machine's index into [`crate::backend::InstrInfo::sched`].
    /// `usize::MAX` for a model that is not one of a target's machines (the
    /// generic fallback), whose instructions all cost
    /// [`InstrSchedClass::DEFAULT`].
    pub id: usize,
    pub issue_width: u16,
    pub frontend: Option<Frontend>,
    pub resources: &'static [ProcUnit],
    pub buffers: &'static [BufferSize],
    /// Ordered pipeline stages; each phase's index is its cycle offset from issue.
    /// Empty when the machine declares no `pipeline` (e.g. an out-of-order core
    /// whose timing is given as scalar latencies).
    pub pipeline: &'static [PipelinePhase],
    /// Forwarding/bypass paths between resources.
    pub forwards: &'static [Forward],
    /// Physical register-file sizes for renaming, keyed by physical-file name. A
    /// file absent here defaults to its architectural register count.
    pub reg_files: &'static [RegFile],
    /// Ordered fusion rules. The first matching contiguous sequence supplies
    /// its explicit schedule. An unknown guard operand prevents fusion.
    pub fusions: &'static [FusionPattern],
}

/// One position in a contiguous fusion pattern. Any listed operation matches.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FusionStep {
    pub ops: &'static [&'static str],
}

/// A named operand of a particular instruction in the matched sequence.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FusionOperandRef {
    pub step: usize,
    pub name: &'static str,
}

/// A pure value available before instruction execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FusionValue {
    Operand(FusionOperandRef),
    Regnum(FusionOperandRef),
    OperandWidth(FusionOperandRef),
    EncodedByte { step: usize, index: usize },
    Pc(usize),
    Width(usize),
    Integer(i128),
    Add(&'static FusionValue, &'static FusionValue),
    Sub(&'static FusionValue, &'static FusionValue),
    Mul(&'static FusionValue, &'static FusionValue),
    Div(&'static FusionValue, &'static FusionValue),
}

/// A pure guard over matched instruction instances. Missing facts evaluate to
/// unknown, which blocks this rule and all lower-priority rules at that point.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FusionExpr {
    True,
    And(&'static [FusionExpr]),
    Or(&'static [FusionExpr]),
    Not(&'static FusionExpr),
    Eq(FusionValue, FusionValue),
    Ne(FusionValue, FusionValue),
    Lt(FusionValue, FusionValue),
    Le(FusionValue, FusionValue),
    Gt(FusionValue, FusionValue),
    Ge(FusionValue, FusionValue),
    SameRegister(FusionValue, FusionValue),
    OverlapRegister(FusionValue, FusionValue),
    SameBlock {
        first: usize,
        second: usize,
        bytes: u64,
    },
    Aligned {
        step: usize,
        bytes: u64,
    },
}

/// A register input or output of a fused micro-op.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FusionOperandSelector {
    Operand(FusionOperandRef),
    AllInputs(usize),
    AllOutputs(usize),
}

/// One memory access of a matched instruction, or all its accesses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FusionMemoryRef {
    pub step: usize,
    pub index: Option<usize>,
}

/// One named execution operation inside a fused schedule.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FusionMicroOp {
    pub name: &'static str,
    pub routes: &'static [ResourceRoute],
    /// Reuse one matched instruction's class routes for legacy rules.
    pub inherit_routes: Option<usize>,
    pub inputs: &'static [FusionOperandSelector],
    pub outputs: &'static [FusionOperandSelector],
    pub depends_on: &'static [&'static str],
    pub read_cycle: u16,
    pub write_cycle: u16,
    /// Original data-memory records served by this micro-op.
    pub memory: &'static [FusionMemoryRef],
    /// Original instruction positions whose branch resolves with this uop.
    pub control_steps: &'static [usize],
}

/// Members that share one allocation at a pipeline stage. The groups of each
/// stage must form a partition of all matched members in program order.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FusionStageGroup {
    pub steps: &'static [usize],
    pub slots: u16,
}

/// Pipeline costs paid once for a matched sequence.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FusionSchedule {
    pub decode_uops: u16,
    /// Storage and delivery cost in the decoded-instruction cache.
    pub decoded_cache_uops: u16,
    pub decoder: Option<&'static str>,
    pub decode_cycles: u16,
    pub rename_slots: u16,
    pub rob_slots: u16,
    pub retire_slots: u16,
    /// Empty arrays use the corresponding scalar cost for the whole sequence.
    pub decode_groups: &'static [FusionStageGroup],
    pub rename_groups: &'static [FusionStageGroup],
    pub rob_groups: &'static [FusionStageGroup],
    pub retire_groups: &'static [FusionStageGroup],
    pub uops: &'static [FusionMicroOp],
}

/// One ordered rule over a finite contiguous sequence.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FusionPattern {
    pub name: &'static str,
    pub steps: &'static [FusionStep],
    pub guard: FusionExpr,
    pub schedule: FusionSchedule,
}

impl MachineModel {
    pub fn resource(&self, name: &str) -> Option<&ProcUnit> {
        self.resources.iter().find(|r| r.name == name)
    }

    /// The declared default size of a structural buffer (e.g. `"rob"`), if any.
    pub fn buffer(&self, name: &str) -> Option<u32> {
        self.buffers.iter().find(|b| b.name == name).map(|b| b.size)
    }

    /// The declared physical register count of a file (e.g. `"GPR"`), if any.
    pub fn reg_file(&self, name: &str) -> Option<u16> {
        self.reg_files
            .iter()
            .find(|f| f.name == name)
            .map(|f| f.count)
    }

    /// The cycle offset (index) of a named pipeline phase, if declared.
    pub fn phase_cycle(&self, name: &str) -> Option<u16> {
        self.pipeline
            .iter()
            .position(|p| p.name == name)
            .map(|i| i as u16)
    }

    /// The forwarded producer→consumer latency for a result moving from the `from`
    /// resource to the `to` resource, if a bypass path is declared.
    pub fn forward_latency(&self, from: &str, to: &str) -> Option<u16> {
        self.forwards
            .iter()
            .find(|f| f.from == from && f.to == to)
            .map(|f| f.latency)
    }
}
