# Generated by tir-bindgen. Do not edit by hand.
# Typed operation constructors, one class per dialect.

class ptr:
    """Constructors for the `ptr` dialect."""

    @staticmethod
    def store(ctx, value, ptr, **attrs):
        operands = []
        operands.append(value)
        operands.append(ptr)
        return ctx._build_op("ptr", "store", operands, None, attrs)

    @staticmethod
    def alloca(ctx, result_type, **attrs):
        operands = []
        return ctx._build_op("ptr", "alloca", operands, result_type, attrs)

    @staticmethod
    def load(ctx, ptr, result_type, **attrs):
        operands = []
        operands.append(ptr)
        return ctx._build_op("ptr", "load", operands, result_type, attrs)


class builtin:
    """Constructors for the `builtin` dialect."""

    @staticmethod
    def call(ctx, args, result_type, **attrs):
        operands = []
        operands.extend(args)
        return ctx._build_op("builtin", "call", operands, result_type, attrs)

    @staticmethod
    def indirect_call(ctx, callee, args, result_type, **attrs):
        operands = []
        operands.append(callee)
        operands.extend(args)
        return ctx._build_op("builtin", "indirect_call", operands, result_type, attrs)

    @staticmethod
    def trunci(ctx, input, result_type, **attrs):
        operands = []
        operands.append(input)
        return ctx._build_op("builtin", "trunci", operands, result_type, attrs)

    @staticmethod
    def muli(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "muli", operands, result_type, attrs)

    @staticmethod
    def shrsi(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "shrsi", operands, result_type, attrs)

    @staticmethod
    def shli(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "shli", operands, result_type, attrs)

    @staticmethod
    def xori(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "xori", operands, result_type, attrs)

    @staticmethod
    def addi(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "addi", operands, result_type, attrs)

    @staticmethod
    def ori(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "ori", operands, result_type, attrs)

    @staticmethod
    def extui(ctx, input, result_type, **attrs):
        operands = []
        operands.append(input)
        return ctx._build_op("builtin", "extui", operands, result_type, attrs)

    @staticmethod
    def cmpi(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "cmpi", operands, result_type, attrs)

    @staticmethod
    def constant(ctx, result_type, **attrs):
        operands = []
        return ctx._build_op("builtin", "constant", operands, result_type, attrs)

    @staticmethod
    def extsi(ctx, input, result_type, **attrs):
        operands = []
        operands.append(input)
        return ctx._build_op("builtin", "extsi", operands, result_type, attrs)

    @staticmethod
    def shrui(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "shrui", operands, result_type, attrs)

    @staticmethod
    def andi(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "andi", operands, result_type, attrs)

    @staticmethod
    def subi(ctx, lhs, rhs, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        return ctx._build_op("builtin", "subi", operands, result_type, attrs)

    @staticmethod
    def module(ctx, **attrs):
        operands = []
        return ctx._build_op("builtin", "module", operands, None, attrs)

    @staticmethod
    def module_end(ctx, **attrs):
        operands = []
        return ctx._build_op("builtin", "module_end", operands, None, attrs)

    @staticmethod
    def cond_br(ctx, condition, true_args, false_args, **attrs):
        operands = []
        operands.append(condition)
        operands.extend(true_args)
        operands.extend(false_args)
        return ctx._build_op("builtin", "cond_br", operands, None, attrs)

    @staticmethod
    def br(ctx, dest_args, **attrs):
        operands = []
        operands.extend(dest_args)
        return ctx._build_op("builtin", "br", operands, None, attrs)

    @staticmethod
    def func(ctx, **attrs):
        operands = []
        return ctx._build_op("builtin", "func", operands, None, attrs)

    @staticmethod
    def return_(ctx, value, **attrs):
        operands = []
        operands.append(value)
        return ctx._build_op("builtin", "return", operands, None, attrs)


class scf:
    """Constructors for the `scf` dialect."""

    @staticmethod
    def if_(ctx, condition, **attrs):
        operands = []
        operands.append(condition)
        return ctx._build_op("scf", "if", operands, None, attrs)

    @staticmethod
    def yield_(ctx, value, **attrs):
        operands = []
        operands.append(value)
        return ctx._build_op("scf", "yield", operands, None, attrs)

    @staticmethod
    def for_(ctx, lower_bound, upper_bound, step, **attrs):
        operands = []
        operands.append(lower_bound)
        operands.append(upper_bound)
        operands.append(step)
        return ctx._build_op("scf", "for", operands, None, attrs)

    @staticmethod
    def while_(ctx, condition, **attrs):
        operands = []
        operands.append(condition)
        return ctx._build_op("scf", "while", operands, None, attrs)


class vector:
    """Constructors for the `vector` dialect."""

    @staticmethod
    def mul(ctx, lhs, rhs, vl, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        operands.append(vl)
        return ctx._build_op("vector", "mul", operands, result_type, attrs)

    @staticmethod
    def add(ctx, lhs, rhs, vl, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        operands.append(vl)
        return ctx._build_op("vector", "add", operands, result_type, attrs)

    @staticmethod
    def sub(ctx, lhs, rhs, vl, result_type, **attrs):
        operands = []
        operands.append(lhs)
        operands.append(rhs)
        operands.append(vl)
        return ctx._build_op("vector", "sub", operands, result_type, attrs)


