//! Python backend: emit one class per dialect, each with a static constructor
//! per op. Constructors delegate to `Context._build_op`, which renders the op
//! textually and parses it, so no per-op formatting logic lives here.

use crate::OpDesc;

const KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

/// Reserved parameter names used by the generated signatures.
const RESERVED: &[&str] = &["ctx", "result_type", "attrs", "operands"];

/// Turn an op or field name into a valid, non-colliding Python identifier.
fn ident(name: &str, reserved: &[&str]) -> String {
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() || s.chars().next().unwrap().is_ascii_digit() {
        s.insert(0, '_');
    }
    if KEYWORDS.contains(&s.as_str()) || reserved.contains(&s.as_str()) {
        s.push('_');
    }
    s
}

pub fn emit(ops: &[OpDesc]) -> String {
    let mut out = String::from(
        "# Generated by tir-bindgen. Do not edit by hand.\n\
         # Typed operation constructors, one class per dialect.\n\n",
    );

    // Group by dialect, preserving first-seen order.
    let mut dialects: Vec<&str> = Vec::new();
    for op in ops {
        if !dialects.contains(&op.dialect.as_str()) {
            dialects.push(&op.dialect);
        }
    }

    for dialect in dialects {
        out.push_str(&format!("class {}:\n", ident(dialect, &[])));
        out.push_str(&format!(
            "    \"\"\"Constructors for the `{dialect}` dialect.\"\"\"\n\n"
        ));
        for op in ops.iter().filter(|o| o.dialect == dialect) {
            emit_op(op, &mut out);
        }
        out.push('\n');
    }
    out
}

fn emit_op(op: &OpDesc, out: &mut String) {
    let fn_name = ident(&op.name, &[]);
    let params: Vec<String> = op
        .operands
        .iter()
        .map(|f| ident(&f.name, RESERVED))
        .collect();

    let mut sig = String::from("ctx");
    for p in &params {
        sig.push_str(", ");
        sig.push_str(p);
    }
    let has_results = !op.results.is_empty();
    if has_results {
        sig.push_str(", result_type");
    }
    sig.push_str(", **attrs");

    out.push_str("    @staticmethod\n");
    out.push_str(&format!("    def {fn_name}({sig}):\n"));
    out.push_str("        operands = []\n");
    for (p, f) in params.iter().zip(&op.operands) {
        if f.variadic {
            out.push_str(&format!("        operands.extend({p})\n"));
        } else {
            out.push_str(&format!("        operands.append({p})\n"));
        }
    }
    let result_arg = if has_results { "result_type" } else { "None" };
    out.push_str(&format!(
        "        return ctx._build_op(\"{}\", \"{}\", operands, {result_arg}, attrs)\n\n",
        op.dialect, op.name
    ));
}
