#ifndef TIR_H
#define TIR_H

#pragma once

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct TirContext TirContext;
typedef struct TirPassManager TirPassManager;
#define TIR_INVALID_ID UINT32_MAX

/* Attribute kind codes returned by tir_op_attribute_kind. */
#define TIR_ATTR_STR 0
#define TIR_ATTR_INT 1
#define TIR_ATTR_UINT 2
#define TIR_ATTR_F32 3
#define TIR_ATTR_F64 4
#define TIR_ATTR_BOOL 5
#define TIR_ATTR_ARRAY 6
#define TIR_ATTR_DICT 7
#define TIR_ATTR_REGISTER 8
#define TIR_ATTR_TYPE 9
#define TIR_ATTR_BLOCK 10

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a context preloaded with the default dialects (builtin, ptr, scf,
 * vector). Free with [`tir_context_destroy`].
 */
TirContext *tir_context_create(void);

/**
 * Destroy a context created by [`tir_context_create`]. Null is ignored.
 *
 * # Safety
 * `ctx` must be null or a context from [`tir_context_create`] not yet destroyed.
 */
void tir_context_destroy(TirContext *ctx);

/**
 * Message of the most recent failure on this thread, or null if none. The
 * pointer is valid until the next TIR call on the same thread.
 */
const char *tir_last_error(void);

/**
 * The schema of every registered operation as a JSON array (dialect, name,
 * operands, results, attributes, interfaces). Enables generating typed
 * language bindings without per-op code. Free with [`tir_string_free`].
 */
char *tir_schema_json(void);

/**
 * Free a string returned by the TIR FFI. Null is ignored.
 *
 * # Safety
 * `s` must be null or a string returned by this library, not yet freed.
 */
void tir_string_free(char *s);

/**
 * Parse a textual module from `src` (`len` bytes). Returns the module op id, or
 * [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context; `src` must be null or readable for `len` bytes.
 */
uint32_t tir_parse_module(const TirContext *ctx, const char *src, uintptr_t len);

/**
 * Render the op `id` to a newly allocated C string, or null on error. Free the
 * result with [`tir_string_free`].
 *
 * # Safety
 * `ctx` must be a valid context from [`tir_context_create`].
 */
char *tir_op_to_string(const TirContext *ctx, uint32_t id);

/**
 * Parse an MLIR-style pass pipeline (e.g. `builtin.func(mem2reg)`) from a
 * null-terminated string. Returns a manager handle, or null on error. Free
 * with [`tir_pipeline_destroy`].
 *
 * # Safety
 * `spec` must be null or a valid NUL-terminated C string.
 */
TirPassManager *tir_pipeline_parse(const char *spec);

/**
 * Run a parsed pipeline over the op `root` in `ctx`. Returns false on error.
 *
 * # Safety
 * `pm` must be a valid pipeline and `ctx` a valid context, or null.
 */
bool tir_pipeline_run(TirPassManager *pm, const TirContext *ctx, uint32_t root);

/**
 * Destroy a pipeline created by [`tir_pipeline_parse`]. Null is ignored.
 *
 * # Safety
 * `pm` must be null or a pipeline from [`tir_pipeline_parse`] not yet destroyed.
 */
void tir_pipeline_destroy(TirPassManager *pm);

/**
 * Name of op `op` as an owned C string, or null on error. Free with `tir_string_free`.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
char *tir_op_name(const TirContext *ctx, uint32_t op);

/**
 * Dialect of op `op` as an owned C string, or null on error. Free with `tir_string_free`.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
char *tir_op_dialect(const TirContext *ctx, uint32_t op);

/**
 * Number of operands of op `op`, or `usize::MAX` on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uintptr_t tir_op_num_operands(const TirContext *ctx, uint32_t op);

/**
 * The `i`-th operand value id of op `op`, or [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_op_operand(const TirContext *ctx, uint32_t op, uintptr_t i);

/**
 * Number of results of op `op`, or `usize::MAX` on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uintptr_t tir_op_num_results(const TirContext *ctx, uint32_t op);

/**
 * The `i`-th result value id of op `op`, or [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_op_result(const TirContext *ctx, uint32_t op, uintptr_t i);

/**
 * Number of regions of op `op`, or `usize::MAX` on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uintptr_t tir_op_num_regions(const TirContext *ctx, uint32_t op);

/**
 * The `i`-th region id of op `op`, or [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_op_region(const TirContext *ctx, uint32_t op, uintptr_t i);

/**
 * Type id of value `value`, or [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_value_type(const TirContext *ctx, uint32_t value);

/**
 * Number of blocks in region `region`, or `usize::MAX` on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uintptr_t tir_region_num_blocks(const TirContext *ctx, uint32_t region);

/**
 * The `i`-th block id of region `region`, or [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_region_block(const TirContext *ctx, uint32_t region, uintptr_t i);

/**
 * Number of operations in block `block`, or `usize::MAX` on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uintptr_t tir_block_num_ops(const TirContext *ctx, uint32_t block);

/**
 * The `i`-th operation id of block `block`, or [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_block_op(const TirContext *ctx, uint32_t block, uintptr_t i);

/**
 * Number of block arguments of block `block`, or `usize::MAX` on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uintptr_t tir_block_num_args(const TirContext *ctx, uint32_t block);

/**
 * The `i`-th block-argument value id of block `block`, or [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_block_arg(const TirContext *ctx, uint32_t block, uintptr_t i);

/**
 * Parse a type from a null-terminated spec (e.g. `!i32`). Returns its id, or
 * [`TIR_INVALID_ID`] on error.
 *
 * # Safety
 * `ctx` must be a valid context handle; `spec` must be null or a valid
 * NUL-terminated C string.
 */
uint32_t tir_type_parse(const TirContext *ctx, const char *spec);

/**
 * Render type `ty` to an owned C string, or null on error. Free with `tir_string_free`.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
char *tir_type_to_string(const TirContext *ctx, uint32_t ty);

/**
 * Number of attributes of op `op`, or `usize::MAX` on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uintptr_t tir_op_num_attributes(const TirContext *ctx, uint32_t op);

/**
 * Name of the `i`-th attribute of op `op` as an owned C string, or null on
 * error. Free with `tir_string_free`.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
char *tir_op_attribute_name(const TirContext *ctx, uint32_t op, uintptr_t i);

/**
 * Kind code of the `i`-th attribute of op `op` (see the `TIR_ATTR_*` macros),
 * or `-1` on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
int32_t tir_op_attribute_kind(const TirContext *ctx, uint32_t op, uintptr_t i);

/**
 * Read a signed-int attribute into `*out`. Returns false if the attribute is a
 * different kind or on error.
 *
 * # Safety
 * `ctx` must be a valid context handle; `out` must be null or a writable `int64_t`.
 */
bool tir_op_attribute_int(const TirContext *ctx, uint32_t op, uintptr_t i, int64_t *out);

/**
 * Read an unsigned-int attribute into `*out`. Returns false on kind mismatch or error.
 *
 * # Safety
 * `ctx` must be a valid context handle; `out` must be null or a writable `uint64_t`.
 */
bool tir_op_attribute_uint(const TirContext *ctx, uint32_t op, uintptr_t i, uint64_t *out);

/**
 * Read a floating-point attribute (`F32` or `F64`) into `*out`. Returns false
 * on kind mismatch or error.
 *
 * # Safety
 * `ctx` must be a valid context handle; `out` must be null or a writable `double`.
 */
bool tir_op_attribute_float(const TirContext *ctx, uint32_t op, uintptr_t i, double *out);

/**
 * Read a boolean attribute into `*out`. Returns false on kind mismatch or error.
 *
 * # Safety
 * `ctx` must be a valid context handle; `out` must be null or a writable `bool`.
 */
bool tir_op_attribute_bool(const TirContext *ctx, uint32_t op, uintptr_t i, bool *out);

/**
 * Value of a string attribute as an owned C string, or null on kind mismatch or
 * error. Free with `tir_string_free`.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
char *tir_op_attribute_string(const TirContext *ctx, uint32_t op, uintptr_t i);

/**
 * Type id of a type attribute, or [`TIR_INVALID_ID`] on kind mismatch or error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_op_attribute_type(const TirContext *ctx, uint32_t op, uintptr_t i);

/**
 * Block id of a block-reference attribute, or [`TIR_INVALID_ID`] on kind
 * mismatch or error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_op_attribute_block(const TirContext *ctx, uint32_t op, uintptr_t i);

/**
 * Parse a single detached operation from `src` (`len` bytes), returning its id
 * or [`TIR_INVALID_ID`] on error. Operand references resolve by numeric value
 * id (e.g. `%5` is value 5), so operands can be wired to existing values; the
 * op's results get fresh value ids (queryable with `tir_op_result`). The op is
 * not placed in any block until inserted with `tir_block_append_op`.
 *
 * # Safety
 * `ctx` must be a valid context handle; `src` must be null or readable for `len` bytes.
 */
uint32_t tir_parse_op(const TirContext *ctx, const char *src, uintptr_t len);

/**
 * Create an empty region, returning its id.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
uint32_t tir_region_create(const TirContext *ctx);

/**
 * Create a block with `n` arguments of the given type ids, returning its id.
 *
 * # Safety
 * `ctx` must be a valid context handle; `arg_types` must be null or readable
 * for `n` `uint32_t`s.
 */
uint32_t tir_block_create(const TirContext *ctx, const uint32_t *arg_types, uintptr_t n);

/**
 * Append block `block` to region `region`. Returns false on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
bool tir_region_append_block(const TirContext *ctx, uint32_t region, uint32_t block);

/**
 * Append op `op` to the end of block `block`. Returns false on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
bool tir_block_append_op(const TirContext *ctx, uint32_t block, uint32_t op);

/**
 * Insert op `op` into block `block` at `index`. Returns false on error,
 * including when `index` exceeds the block length.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
bool tir_block_insert_op(const TirContext *ctx, uint32_t block, uintptr_t index, uint32_t op);

/**
 * Remove op `op` from block `block`. Returns false if the op was not present
 * or on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
bool tir_block_remove_op(const TirContext *ctx, uint32_t block, uint32_t op);

/**
 * Replace op `old` with op `new` in block `block`, preserving position.
 * Returns false if `old` was not present or on error.
 *
 * # Safety
 * `ctx` must be a valid context handle.
 */
bool tir_block_replace_op(const TirContext *ctx, uint32_t block, uint32_t old, uint32_t new_);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TIR_H */
