[suite]
package = "fixture"

[llvm]
prepare = ["gcc", "-E", "-P", "{level}", "{flags}", "{source}", "-o", "{output}"]
version = ["gcc", "-dumpfullversion"]

[[compiler]]
name = "gcc"
compile = ["gcc", "{level}", "{flags}", "-c", "{source}", "-o", "{output}"]
link = ["gcc", "{objects}", "{link_flags}", "-o", "{output}"]

[[compiler]]
name = "tir"
input = "llvm"
compile = ["gcc", "-x", "c", "-c", "{source}", "-o", "{output}"]
link = ["gcc", "{objects}", "{link_flags}", "-o", "{output}"]
