[package]
name = "tir-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
globset.workspace = true
libc = "0.2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2 = "0.8.2"
tempfile = "3.27.0"

[lib]
bench = false

[lints]
workspace = true
