name: Fuzz

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build fuzz targets
        run: cargo check -p tir-fuzz --bins

  fuzz:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        target:
          - tmdl-fuzz
          - riscv-assembly-fuzz
          - arm64-assembly-fuzz
      max-parallel: 3
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz --locked
      - name: Fuzz
        run: cargo +nightly fuzz run ${{ matrix.target }} -- -max_total_time=60 -max_len=16384
