//! x86-64 backend prototype.
//!
//! The instruction set, register file and assembly syntax are generated from
//! the TMDL descriptions in `defs/` at build time. This crate wires the
//! generated dialect together, exposes an Intel-syntax assembler
//! parser/printer pair, and exposes the instruction encoders. See `BLOCKERS.md`
//! for the x86 features the current TMDL cannot express.

pub use isa::{X86_64Dialect, instruction_encoders, instruction_patchers};

mod isa {
    // The included file is generated by `build.rs` from the TMDL sources; its
    // encoders/patchers and target-query helpers are only partly used by this
    // prototype (there is no `TargetMachine` impl yet), so the generated code's
    // dead-code and unused-parameter lints are allowed here.
    #![allow(dead_code, unused_variables, unused_mut, clippy::all)]

    use tir::Operation;
    use tir::helpers::{dialect, operation};

    include!(concat!(env!("OUT_DIR"), "/x86_64.rs"));

    dialect! {
        X86_64Dialect {
            name: "x86_64",
            operations: [
                // Register/register ALU
                AddOp,
                SubOp,
                AndOp,
                OrOp,
                XorOp,
                MovOp,
                // Register/immediate ALU
                AddImmOp,
                AndImmOp,
                OrImmOp,
                XorImmOp,
                MovImmOp,
                // Shift by immediate
                ShlImmOp,
                ShrImmOp,
                SarImmOp,
                // Control flow
                JmpOp,
                CallOp,
                RetOp
            ],
        }
    }

    impl X86_64Dialect {
        pub fn get_asm_parser(&self) -> tir_be_common::AsmParser {
            tir_be_common::AsmParser::new(get_instruction_parsers(Feature::ALL).0)
        }

        pub fn get_asm_printer(&self) -> tir_be_common::AsmPrinter {
            tir_be_common::AsmPrinter::new(get_instruction_printers())
        }
    }

    /// Per-mnemonic machine-code encoders, keyed by operation name.
    pub fn instruction_encoders()
    -> std::collections::HashMap<String, tir_be_common::binary::InstructionEncoder> {
        get_instruction_encoders()
    }

    /// Per-mnemonic relocation patchers, keyed by operation name.
    pub fn instruction_patchers()
    -> std::collections::HashMap<String, tir_be_common::binary::InstructionPatcher> {
        get_instruction_patchers()
    }
}
